routes/web.php
<?php


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix' => 'account'], function () {
    Route::get('/', 'CcpsCore\AccountController@index')->name('account');
    Route::get('/settings', 'CcpsCore\AccountController@settings')->name('account.settings');
    Route::post('/settings', 'CcpsCore\AccountController@updateSettings')->name('account.settings.update');
    Route::get('/profile', 'CcpsCore\AccountController@profile')->name('profile.show');
    Route::get('/profile/edit', 'CcpsCore\AccountController@editProfile')->name('profile.edit');
    Route::patch('/profile/', 'CcpsCore\AccountController@updateProfile')->name('profile.update');

    Route::prefix('tokens')->name('account.tokens.')->group(function () {
        Route::get('/', 'CcpsCore\AccountController@tokens')->name('index');
        Route::get('create', 'CcpsCore\AccountController@createToken')->name('create');
        Route::post('/', 'CcpsCore\AccountController@storeToken')->name('store');
        Route::get('{token}', 'CcpsCore\AccountController@editToken')->name('edit');
        Route::patch('{token}', 'CcpsCore\AccountController@updateToken')->name('update');
        Route::delete('{token}', 'CcpsCore\AccountController@revokeToken')->name('revoke');
    });

    Route::group(['prefix' => 'notifications'], function () {
        Route::get('/', 'CcpsCore\AccountController@notifications')->name('account.notifications.index');
        Route::get('/channels/create', 'CcpsCore\AccountController@createChannel')->name('account.notifications.channels.create');
        Route::post('/channels/create', 'CcpsCore\AccountController@storeChannel')->name('account.notifications.channels.store');
        Route::delete('/channels/{channel}', 'CcpsCore\AccountController@destroyChannel')->name('account.notifications.channels.destroy');
        Route::get(
            '/channels/{channel}/resend-verification',
            'CcpsCore\ChannelVerificationController@resend'
        )->name('account.notifications.channels.resend-verification');
        Route::get(
            '/channels/{channel}/verify',
            'CcpsCore\ChannelVerificationController@verify'
        )->name('account.notifications.channels.verify');
        Route::get(
            '/channels/{channel}/test',
            'CcpsCore\ChannelVerificationController@test'
        )->name('account.notifications.channels.test');

        Route::get('/configure', 'CcpsCore\AccountController@configure')->name('account.notifications.configure');
        Route::post('/configure', 'CcpsCore\AccountController@configureSave')->name('account.notifications.configure.save');
    });
});

// CCPS Core routes
Uncgits\Ccps\Support\Facades\CcpsCore::routes();

// For local auth
Auth::routes();

// Socialite - User Account OAuth Routes
Route::get('auth/{provider}', 'CcpsCore\AuthController@redirectToProvider')->name('oauth');
Route::get('auth/{provider}/callback', 'CcpsCore\AuthController@handleProviderCallback')->name('oauth.callback');

Route::get('/', 'CanvasController@index')->name('home');

Route::prefix('live')->name('live.')->group(function () {
    Route::get('accounts', 'Canvas\Live\AccountsController@index')->name('accounts.index');


    Route::prefix('courses')->name('courses.')->group(function () {
        Route::get('/', 'Canvas\Live\CourseController@index')->name('index');
        Route::get('/show', 'Canvas\Live\CourseController@show')->name('show');
        Route::get('/download-enrollments', 'Canvas\Live\CourseController@downloadEnrollments')->name('download-enrollments');
    });

    Route::prefix('users')->name('users.')->group(function () {
        Route::get('/', 'Canvas\Live\UserController@index')->name('index');
        Route::get('/show', 'Canvas\Live\UserController@show')->name('show');
        Route::get('/course', 'Canvas\Live\UserController@course')->name('course');
        Route::get('/courses', 'Canvas\Live\UserController@courses')->name('courses');
    });

    Route::prefix('enrollments')->name('enrollments.')->group(function () {
        Route::get('/', 'Canvas\Live\EnrollmentController@index')->name('index');
        Route::get('/download', 'Canvas\Live\EnrollmentController@download')->name('download-user-enrollments');
    });

    Route::prefix('lookups')->name('lookups.')->group(function () {
        Route::get('/', 'Canvas\Live\LiveLookupController@index')->name('index');
    });
});

Route::prefix('courses')->name('courses.')->group(function () {
    Route::get('/create', 'Canvas\CourseController@create')->name('create');
    Route::post('/create', 'Canvas\CourseController@store')->name('store');
    Route::patch('/update', 'Canvas\CourseController@update')->name('update');

    Route::get('/list-roles-select-element', 'Canvas\CourseController@listRolesSelectElement')->name('list-roles-select-element');
    Route::post('/removeSisId', 'Canvas\CourseController@removeSisId')->name('removeSisId');
});

Route::group(['prefix' => 'crosslist'], function () {
    Route::get('/index', 'Canvas\CrosslistController@index')->name('crosslist.index');
    Route::get('/create', 'Canvas\CrosslistController@create')->name('crosslist.create');
    Route::redirect('/bulk', '/crosslist/create');
    Route::get('/decrosslist', 'Canvas\CrosslistController@decrosslist')->name('crosslist.decrosslist');
    Route::post('/destroy', 'Canvas\CrosslistController@destroy')->name('crosslist.destroy');
    Route::get('/report', 'CrosslistController@index')->name('crosslist-report.index');
});

Route::group(['prefix' => 'enrollmentrequests'], function () {
    Route::get('/', 'Canvas\EnrollmentrequestsController@index')->name('enrollmentrequests.index');
    Route::get('/all', 'Canvas\EnrollmentrequestsController@all')->name('enrollmentrequests.all');
    Route::get('/create', 'Canvas\EnrollmentrequestsController@create')->name('enrollmentrequests.create');
    Route::get('/show', 'Canvas\EnrollmentrequestsController@show')->name('enrollmentrequests.show');
    Route::get('/{enrollmentRequest}/edit', 'Canvas\EnrollmentrequestsController@edit')->name('enrollmentrequests.edit');
    Route::patch('/{enrollmentRequest}', 'Canvas\EnrollmentrequestsController@update')->name('enrollmentrequests.update');
    Route::get('/delete', 'Canvas\EnrollmentrequestsController@delete')->name('enrollmentrequests.delete');

    Route::get(
        '/create-in-canvas',
        'Canvas\EnrollmentrequestsController@createInCanvas'
    )->name('enrollmentrequests.create-in-canvas');
    Route::get('/reject', 'Canvas\EnrollmentrequestsController@reject')->name('enrollmentrequests.reject');

    Route::post('/store', 'Canvas\EnrollmentrequestsController@store')->name('enrollmentrequests.store');
    Route::delete(
        '/destroy',
        'Canvas\EnrollmentrequestsController@destroy'
    )->name('enrollmentrequests.destroy');

    Route::get(
        '/list-accounts',
        'Canvas\EnrollmentrequestsController@listAccounts'
    )->name('enrollmentrequests.list-accounts');
    Route::get(
        '/list-roles',
        'Canvas\EnrollmentrequestsController@listRoles'
    )->name('enrollmentrequests.list-roles');
    Route::get(
        '/list-roles-select-element',
        'Canvas\EnrollmentrequestsController@listRolesSelectElement'
    )->name('enrollmentrequests.list-roles-select-element');
});


Route::group(['prefix' => 'lti'], function () {
    Route::get('/', 'Canvas\LtiController@index')->name('lti.index');
    Route::get('/tool-edit', 'Canvas\LtiController@tooledit')->name('lti.tool.edit');
    Route::get('/tool-delete', 'Canvas\LtiController@tooldelete')->name('lti.tool.delete');
    Route::get('/tool-create', 'Canvas\LtiController@toolcreate')->name('lti.tool.create');
    Route::patch('/tool-update', 'Canvas\LtiController@toolupdate')->name('lti.tool.update');
    Route::post('/tool-store', 'Canvas\LtiController@toolstore')->name('lti.tool.store');
    Route::post('/tool-destroy', 'Canvas\LtiController@tooldestroy')->name('lti.tool.destroy');

    Route::get('/inventory', 'Canvas\LtiController@inventory')->name('lti.inventory.index');
    Route::get('/inventory-edit', 'Canvas\LtiController@inventoryedit')->name('lti.inventory.edit');
    Route::get('/inventory-delete', 'Canvas\LtiController@inventorydelete')->name('lti.inventory.delete');
    Route::get('/inventory-create', 'Canvas\LtiController@inventorycreate')->name('lti.inventory.create');
    Route::patch('/inventory-update', 'Canvas\LtiController@inventoryupdate')->name('lti.inventory.update');
    Route::post('/inventory-store', 'Canvas\LtiController@inventorystore')->name('lti.inventory.store');
    Route::post('/inventory-destroy', 'Canvas\LtiController@inventorydestroy')->name('lti.inventory.destroy');

    Route::get('/enrollment', 'Canvas\LtiController@enrollment')->name('lti.enrollment.index');
});

Route::group(['prefix' => 'page-view-audits'], function () {
    Route::get('/', 'Canvas\PageViewAuditController@index')->name('canvas.page-view-audits.index');
    Route::post('/results', 'Canvas\PageViewAuditController@results')->name('canvas.page-view-audits.results');
});

Route::group(['prefix' => 'nav-item-replacer'], function () {
    Route::get('/', 'NavItemReplacerController@index')->name('canvas.nav-item-replacer.index');
    Route::post('/review', 'NavItemReplacerController@review')->name('canvas.nav-item-replacer.review');
    Route::post('/', 'NavItemReplacerController@replace')->name('canvas.nav-item-replacer.replace');
});

Route::group(['prefix' => 'course-activity-report'], function () {
    Route::get('/', 'CourseActivityReportController@index')->name('canvas.course-activity-report.index');

resources/views/index.blade.php
@extends('layouts.wrapper', [
'pageTitle' => 'Home'
])

@section('content')
{!! Breadcrumbs::render('index') !!}
@if($user)
<h1>Canvas Tools</h1>
<div class="row">
    @permission('canvas.*')
    <div class="col-6 mb-3">
        <h2>Live Lookup tools</h2>
        <div class="row">
            @permission('canvas.accounts.view')
                @include('components.panel-nav', [
                    'url' => route('live.accounts.index'),
                    'fa' => 'fas fa-list',
                    'title' => 'Canvas Accounts'
                ])
            @endpermission
            @permission('canvas.users.view')
                @include('components.panel-nav', [
                    'url' => route('live.users.index'),
                    'fa' => 'fas fa-user-circle',
                    'title' => 'User Lookup'
                ])
            @endpermission
            @permission('canvas.courses.view')
                @include('components.panel-nav', [
                    'url' => route('live.courses.index'),
                    'fa' => 'fas fa-search',
                    'title' => 'Course Search'
                ])
            @endpermission
            @permission('live-lookups.view')
                @include('components.panel-nav', [
                    'url' => route('live.lookups.index'),
                    'fa' => 'fas fa-clipboard-list',
                    'title' => 'Live Lookup Log'
                ])
            @endpermission
        </div>
    </div>
    @endpermission

    @permission('crosslist.create|enrollmentrequests.*')
    <div class="col-6 mb-3">
        <h2>Instructional Technology Support</h2>
        <div class="row">
            @permission('crosslist.create')
                @include('components.panel-nav', [
                    'url' => route('crosslist.index'),
                    'fa' => 'fas fa-sync',
                    'title' => 'Crosslist'
                ])
            @endpermission
            @permission('enrollmentrequests.*')
                @include('components.panel-nav', [
                    'url' => route('enrollmentrequests.index'),
                    'fa' => 'fas fa-user-plus',
                    'title' => 'Enrollment Requests'
                ])
            @endpermission
            @permission('batch-sandbox.*')
                @include('components.panel-nav', [
                    'url' => route('batch-sandbox-courses.index'),
                    'fa' => 'fas fa-sitemap',
                    'title' => 'Batch Sandbox Courses'
                ])
            @endpermission
        </div>
    </div>
    @endpermission

    @permission('course-activity-report.edit|lti-reports.*|quiz-log-reports.*')
    <div class="col-6 mb-3">
        <h2>Reporting Tools</h2>
        <div class="row">
            @permission('course-activity-report.edit')
                @include('components.panel-nav', [
                    'url' => route('canvas.course-activity-report.index'),
                    'fa' => 'fas fa-book',
                    'title' => 'Course Activity Reports'
                ])
            @endpermission
            @permission('lti-reports.*')
                @include('components.panel-nav', [
                    'url' => route('canvas.lti-reports.index'),
                    'fa' => 'fas fa-toolbox',
                    'title' => 'LTI Reports'
                ])
            @endpermission
            @permission('quiz-log-reports.*')
                @include('components.panel-nav', [
                    'url' => route('canvas.quiz-log-reports.index'),
                    'fa' => 'fas fa-user-clock',
                    'title' => 'Quiz Log Reports'
                ])
            @endpermission
            @permission('nav-item-reports.*')
                @include('components.panel-nav', [
                    'url' => route('nav-item-reports.index'),
                    'fa' => 'fas fa-map-marked',
                    'title' => 'Nav Item Reports'
                ])
            @endpermission

        </div>
    </div>
    @endpermission

    @permission('canvas.courses.create|manual-enrollments.*|lti.*|page-views.*|nav-item-replacer.*')
    <div class="col-6 mb-3">
        <h2>Canvas Admin Support</h2>
        <div class="row">
            @permission('canvas.courses.create')
                @include('components.panel-nav', [
                    'url' => route('courses.create'),
                    'fa' => 'fas fa-plus',
                    'title' => 'Create a Course'
                ])
            @endpermission
            @permission('manual-enrollments.read')
                @include('components.panel-nav', [
                    'url' => route('manual-enrollments.index'),
                    'fa' => 'fas fa-users',
                    'title' => 'Manual Enrollments'
                ])
            @endpermission
            @permission('lti.read')
                @include('components.panel-nav', [
                    'url' => route('lti.index'),
                    'fa' => 'fab fa-skyatlas',
                    'title' => 'LTI Inventory'
                ])
            @endpermission
            @permission('page-views.read')
                @include('components.panel-nav', [
                    'url' => route('canvas.page-view-audits.index'),
                    'fa' => 'fas fa-glasses',
                    'title' => 'Page View Audit'
                ])
            @endpermission
            @permission('nav-item-replacer.edit')
                @include('components.panel-nav', [
                    'url' => route('canvas.nav-item-replacer.index'),
                    'fa' => 'fas fa-bars',
                    'title' => 'Nav Item Replacer'
                ])
            @endpermission
            @permission('lti.read')
                @include('components.panel-nav', [
                    'url' => route('lti-editor.index'),
                    'fa' => 'fas fa-pencil-alt',
                    'title' => 'LTI Editor'
                ])
            @endpermission
        </div>
    </div>
    @endpermission
</div>

@role('admin')
<div class="col-6 mb-3">
    <h2>Application Administrator</h2>
    <div class="row">
        @include('components.panel-nav', [
            'url' => route('admin'),
            'fa' => 'fas fa-key',
            'title' => 'Administrator'
        ])
    </div>
</div>
@endrole

@else
<h1>{{ config('app.name') }}</h1>
<div class="row">
    <div class="col">
        <p>You are not logged in - please <a href="{{ route('login') }}">log in</a> to proceed.</p>
    </div>
</div>
@endif
@endsection