routes/web.php
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix' => 'account'], function () {
    Route::get('/', 'CcpsCore\AccountController@index')->name('account');
    Route::get('/settings', 'CcpsCore\AccountController@settings')->name('account.settings');
    Route::post('/settings', 'CcpsCore\AccountController@updateSettings')->name('account.settings.update');
    Route::get('/profile', 'CcpsCore\AccountController@profile')->name('profile.show');
    Route::get('/profile/edit', 'CcpsCore\AccountController@editProfile')->name('profile.edit');
    Route::patch('/profile/', 'CcpsCore\AccountController@updateProfile')->name('profile.update');

    Route::prefix('tokens')->name('account.tokens.')->group(function () {
        Route::get('/', 'CcpsCore\AccountController@tokens')->name('index');
        Route::get('create', 'CcpsCore\AccountController@createToken')->name('create');
        Route::post('/', 'CcpsCore\AccountController@storeToken')->name('store');
        Route::get('{token}', 'CcpsCore\AccountController@editToken')->name('edit');
        Route::patch('{token}', 'CcpsCore\AccountController@updateToken')->name('update');
        Route::delete('{token}', 'CcpsCore\AccountController@revokeToken')->name('revoke');
    });

    Route::group(['prefix' => 'notifications'], function () {
        Route::get('/', 'CcpsCore\AccountController@notifications')->name('account.notifications.index');
        Route::get('/channels/create', 'CcpsCore\AccountController@createChannel')->name('account.notifications.channels.create');
        Route::post('/channels/create', 'CcpsCore\AccountController@storeChannel')->name('account.notifications.channels.store');
        Route::delete('/channels/{channel}', 'CcpsCore\AccountController@destroyChannel')->name('account.notifications.channels.destroy');
        Route::get(
            '/channels/{channel}/resend-verification',
            'CcpsCore\ChannelVerificationController@resend'
        )->name('account.notifications.channels.resend-verification');
        Route::get(
            '/channels/{channel}/verify',
            'CcpsCore\ChannelVerificationController@verify'
        )->name('account.notifications.channels.verify');
        Route::get(
            '/channels/{channel}/test',
            'CcpsCore\ChannelVerificationController@test'
        )->name('account.notifications.channels.test');

        Route::get('/configure', 'CcpsCore\AccountController@configure')->name('account.notifications.configure');
        Route::post('/configure', 'CcpsCore\AccountController@configureSave')->name('account.notifications.configure.save');
    });
});

// CCPS Core routes
Uncgits\Ccps\Support\Facades\CcpsCore::routes();

// For local auth
Auth::routes();

// Socialite - User Account OAuth Routes
Route::get('auth/{provider}', 'CcpsCore\AuthController@redirectToProvider')->name('oauth');
Route::get('auth/{provider}/callback', 'CcpsCore\AuthController@handleProviderCallback')->name('oauth.callback');

Route::get('/', 'CanvasController@index')->name('home');

Route::prefix('live')->name('live.')->group(function () {
    Route::get('accounts', 'Canvas\Live\AccountsController@index')->name('accounts.index');


    Route::prefix('courses')->name('courses.')->group(function () {
        Route::get('/', 'Canvas\Live\CourseController@index')->name('index');
        Route::get('/show', 'Canvas\Live\CourseController@show')->name('show');
        Route::get('/download-enrollments', 'Canvas\Live\CourseController@downloadEnrollments')->name('download-enrollments');
    });

    Route::prefix('users')->name('users.')->group(function () {
        Route::get('/', 'Canvas\Live\UserController@index')->name('index');
        Route::get('/show', 'Canvas\Live\UserController@show')->name('show');
        Route::get('/course', 'Canvas\Live\UserController@course')->name('course');
        Route::get('/courses', 'Canvas\Live\UserController@courses')->name('courses');
    });

    Route::prefix('enrollments')->name('enrollments.')->group(function () {
        Route::get('/', 'Canvas\Live\EnrollmentController@index')->name('index');
        Route::get('/download', 'Canvas\Live\EnrollmentController@download')->name('download-user-enrollments');
    });

    Route::prefix('lookups')->name('lookups.')->group(function () {
        Route::get('/', 'Canvas\Live\LiveLookupController@index')->name('index');
    });
});

Route::prefix('courses')->name('courses.')->group(function () {
    Route::get('/create', 'Canvas\CourseController@create')->name('create');
    Route::post('/create', 'Canvas\CourseController@store')->name('store');
    Route::patch('/update', 'Canvas\CourseController@update')->name('update');

    Route::get('/list-roles-select-element', 'Canvas\CourseController@listRolesSelectElement')->name('list-roles-select-element');
    Route::post('/removeSisId', 'Canvas\CourseController@removeSisId')->name('removeSisId');
});

Route::group(['prefix' => 'crosslist'], function () {
    Route::get('/index', 'Canvas\CrosslistController@index')->name('crosslist.index');
    Route::get('/create', 'Canvas\CrosslistController@create')->name('crosslist.create');
    Route::redirect('/bulk', '/crosslist/create');
    Route::get('/decrosslist', 'Canvas\CrosslistController@decrosslist')->name('crosslist.decrosslist');
    Route::post('/destroy', 'Canvas\CrosslistController@destroy')->name('crosslist.destroy');
    Route::get('/report', 'CrosslistController@index')->name('crosslist-report.index');
});

Route::group(['prefix' => 'enrollmentrequests'], function () {
    Route::get('/', 'Canvas\EnrollmentrequestsController@index')->name('enrollmentrequests.index');
    Route::get('/all', 'Canvas\EnrollmentrequestsController@all')->name('enrollmentrequests.all');
    Route::get('/create', 'Canvas\EnrollmentrequestsController@create')->name('enrollmentrequests.create');
    Route::get('/show', 'Canvas\EnrollmentrequestsController@show')->name('enrollmentrequests.show');
    Route::get('/{enrollmentRequest}/edit', 'Canvas\EnrollmentrequestsController@edit')->name('enrollmentrequests.edit');
    Route::patch('/{enrollmentRequest}', 'Canvas\EnrollmentrequestsController@update')->name('enrollmentrequests.update');
    Route::get('/delete', 'Canvas\EnrollmentrequestsController@delete')->name('enrollmentrequests.delete');

    Route::get(
        '/create-in-canvas',
        'Canvas\EnrollmentrequestsController@createInCanvas'
    )->name('enrollmentrequests.create-in-canvas');
    Route::get('/reject', 'Canvas\EnrollmentrequestsController@reject')->name('enrollmentrequests.reject');

    Route::post('/store', 'Canvas\EnrollmentrequestsController@store')->name('enrollmentrequests.store');
    Route::delete(
        '/destroy',
        'Canvas\EnrollmentrequestsController@destroy'
    )->name('enrollmentrequests.destroy');

    Route::get(
        '/list-accounts',
        'Canvas\EnrollmentrequestsController@listAccounts'
    )->name('enrollmentrequests.list-accounts');
    Route::get(
        '/list-roles',
        'Canvas\EnrollmentrequestsController@listRoles'
    )->name('enrollmentrequests.list-roles');
    Route::get(
        '/list-roles-select-element',
        'Canvas\EnrollmentrequestsController@listRolesSelectElement'
    )->name('enrollmentrequests.list-roles-select-element');
});


Route::group(['prefix' => 'lti'], function () {
    Route::get('/', 'Canvas\LtiController@index')->name('lti.index');
    Route::get('/tool-edit', 'Canvas\LtiController@tooledit')->name('lti.tool.edit');
    Route::get('/tool-delete', 'Canvas\LtiController@tooldelete')->name('lti.tool.delete');
    Route::get('/tool-create', 'Canvas\LtiController@toolcreate')->name('lti.tool.create');
    Route::patch('/tool-update', 'Canvas\LtiController@toolupdate')->name('lti.tool.update');
    Route::post('/tool-store', 'Canvas\LtiController@toolstore')->name('lti.tool.store');
    Route::post('/tool-destroy', 'Canvas\LtiController@tooldestroy')->name('lti.tool.destroy');

    Route::get('/inventory', 'Canvas\LtiController@inventory')->name('lti.inventory.index');
    Route::get('/inventory-edit', 'Canvas\LtiController@inventoryedit')->name('lti.inventory.edit');
    Route::get('/inventory-delete', 'Canvas\LtiController@inventorydelete')->name('lti.inventory.delete');
    Route::get('/inventory-create', 'Canvas\LtiController@inventorycreate')->name('lti.inventory.create');
    Route::patch('/inventory-update', 'Canvas\LtiController@inventoryupdate')->name('lti.inventory.update');
    Route::post('/inventory-store', 'Canvas\LtiController@inventorystore')->name('lti.inventory.store');
    Route::post('/inventory-destroy', 'Canvas\LtiController@inventorydestroy')->name('lti.inventory.destroy');

    Route::get('/enrollment', 'Canvas\LtiController@enrollment')->name('lti.enrollment.index');
});

Route::group(['prefix' => 'page-view-audits'], function () {
    Route::get('/', 'Canvas\PageViewAuditController@index')->name('canvas.page-view-audits.index');
    Route::post('/results', 'Canvas\PageViewAuditController@results')->name('canvas.page-view-audits.results');
});

Route::group(['prefix' => 'nav-item-replacer'], function () {
    Route::get('/', 'NavItemReplacerController@index')->name('canvas.nav-item-replacer.index');
    Route::post('/review', 'NavItemReplacerController@review')->name('canvas.nav-item-replacer.review');
    Route::post('/', 'NavItemReplacerController@replace')->name('canvas.nav-item-replacer.replace');
});

Route::group(['prefix' => 'course-activity-report'], function () {
    Route::get('/', 'CourseActivityReportController@index')->name('canvas.course-activity-report.index');
    Route::get('/create', 'CourseActivityReportController@create')->name('canvas.course-activity-report.create');

resources/views/partials/courses/course-info.blade.php
<div class="table-responsive">
    <table class="table table-borderless">
        <tbody>
            <tr>
                <th>Canvas URL</th>
                <td>
                    <a title="View course with ID {{ $course->id }} in Canvas" href="{{ 'https://' . config('canvas-api.configs.' . config('canvas-api.defaults.config') . '.host') . '/courses/' . $course->id . '/settings' }}" target="_blank">
                    {{ 'https://' . config('canvas-api.configs.' . config('canvas-api.defaults.config') . '.host') . '/courses/' . $course->id . '/settings' }}
                    </a>
                </td>
            </tr>
            <tr>
                <th>ID</th>
                <td>{{ $course->id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ $course->name }}</td>
            </tr>
            <tr>
                <th>Workflow State</th>
                <td class="text-{{ $course->workflow_state === 'unpublished' ? 'danger' : 'success' }}">
                    <i class="fas fa-{{ $course->workflow_state === 'unpublished' ? 'times-circle' : 'check-circle' }}"></i>
                    {{ $course->workflow_state }}
                </td>
            </tr>
            <tr>
                <th>Account</th>
                <td>{{ $course->account->name }}</td>
            </tr>
            <tr>
                <th>Total Students</th>
                <td>{{ $course->total_students }}</td>
            </tr>
            <tr>
                <th>Teachers</th>
                <td>
                    @foreach($course->teachers as $teacher)
                    {{ $teacher->display_name }}<br />
                    @endforeach
                </td>
            </tr>
            <tr>
                <th>Created At</th>
                <td>{{ $course->created_at }}</td>
            </tr>
            <tr>
                <th>Start At</th>
                <td>{{ $course->start_at }}</td>
            </tr>
            <tr>
                <th>End At</th>
                <td>{{ $course->end_at }}</td>
            </tr>
            <tr>
                <th>Term</th>
                <td>{{ $course->term->name }}</td>
            </tr>
            <tr>
                <th>Is Public</th>
                <td>{{ $course->is_public }}</td>
            </tr><tr>
                <th>Grading Standard ID</th>
                <td>{{ $course->grading_standard_id }}</td>
            </tr>
            <tr>
                <th>Storage Quota MB</th>
                <td>{{ $course->storage_quota_used_mb }} used of {{ $course->storage_quota_mb }}</td>
            </tr>
            <tr>
                <th>SIS Course ID</th>
                <td>
                    <p>{{ $course->sis_course_id }}</p>
                    @permission('canvas.courses.edit')
                    @if(!empty($course->sis_course_id))
                        {!! Form::open()->method('patch')->route('courses.update') !!}
                        {!! Form::hidden('operation', 'remove_sis_course_id') !!}
                        {!! Form::hidden('course_id', $course->id) !!}
                        {!! Form::submit('<i class="fas fa-unlink"></i> Remove SIS ID')->color('danger')->attrs(['onclick' => 'return confirm("Are you sure? You cannot undo this action.")']) !!}
                        {!! Form::close() !!}
                    @endif
                    @endpermission
                </td>
            </tr>
            <tr>
                <th>Course Object Data from Canvas</th>
                <td>
                    <!-- Button trigger modal -->
                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#courseMeta">
                        <i class="fas fa-list"></i>
                        View course object
                    </button>

                    <!-- Modal -->
                    <div class="modal fade" id="courseMeta" tabindex="-1" role="dialog" aria-labelledby="courseMetaLabel" aria-hidden="true">
                        <div class="modal-dialog modal-lg" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="courseMetaLabel">Course Metadata</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    <pre>{{ json_encode($course, JSON_PRETTY_PRINT) }}</pre>
                                </div>
                            </div>
                        </div>
                    </div>
                </td>
            </tr>
        </tbody>
    </table>
</div>

resources/views/partials/courses/enrollment-list.blade.php
@component('components.paginated-table', ['collection' => $enrollments, 'appends' => request()->except('_token')])
    @slot('table')
        @component('components.table')
            @slot('th')
                <th>Name</th>
                <th>SIS Login ID</th>
                <th>Role</th>
                <th>State</th>
                <th>Created At (local)</th>
            @endslot
            @slot('tbody')
                @foreach ($enrollments as $enrollment)
                    @if ($enrollment->user->sortable_name !== 'Student, Test')
                        <tr>
                            <td>
                                <a href="{{ route('live.users.show', ['id_type' => 'sis_login_id', 'user_id' => $enrollment->user->login_id]) }}">
                                    {{ $enrollment->user->sortable_name }}
                                </a>
                            </td>
                            <td>
                                <a href="{{ route('live.users.show', ['id_type' => 'sis_login_id', 'user_id' => $enrollment->user->login_id]) }}">
                                    {{ $enrollment->user->login_id }}
                                </a>
                            </td>
                            <td>{{ $enrollment->role }}</td>
                            <td>{{ $enrollment->enrollment_state }}</td>
                            <td>{{ \Carbon\Carbon::parse($enrollment->created_at)->setTimezone(config('app.timezone'))->format('Y-m-d H:i:s') }}</td>
                        </tr>
                    @endif
                @endforeach
            @endslot
        @endcomponent
    @endslot
@endcomponent

resources/views/partials/courses/section-list.blade.php
@component('components.table')
    @slot('th')
        <th>Canvas ID</th>
        <th>Name</th>
    @endslot
    @slot('tbody')
        @foreach ($course->sections as $section)
            <tr>
                <td>{{ $section->id }}</td>
                <td>{{ $section->name }}</td>
            </tr>
        @endforeach
    @endslot
@endcomponent

resources/views/partials/courses/tabs-list.blade.php
@component('components.table')
    @slot('th')
        <th>Label</th>
        <th>Position</th>
        <th>Visibile?</th>
    @endslot
    @slot('tbody')
        @foreach ($tabs as $tab)
            <tr>
                <td>{{ $tab->label }}</td>
                <td>{{ $tab->position }}</td>
                <td>{{ ($tab->hidden ?? false) ? 'no' : 'yes' }}</td>
            </tr>
        @endforeach
    @endslot
@endcomponent