routes/web.php
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix' => 'account'], function () {
    Route::get('/', 'CcpsCore\AccountController@index')->name('account');
    Route::get('/settings', 'CcpsCore\AccountController@settings')->name('account.settings');
    Route::post('/settings', 'CcpsCore\AccountController@updateSettings')->name('account.settings.update');
    Route::get('/profile', 'CcpsCore\AccountController@profile')->name('profile.show');
    Route::get('/profile/edit', 'CcpsCore\AccountController@editProfile')->name('profile.edit');
    Route::patch('/profile/', 'CcpsCore\AccountController@updateProfile')->name('profile.update');

    Route::prefix('tokens')->name('account.tokens.')->group(function () {
        Route::get('/', 'CcpsCore\AccountController@tokens')->name('index');
        Route::get('create', 'CcpsCore\AccountController@createToken')->name('create');
        Route::post('/', 'CcpsCore\AccountController@storeToken')->name('store');
        Route::get('{token}', 'CcpsCore\AccountController@editToken')->name('edit');
        Route::patch('{token}', 'CcpsCore\AccountController@updateToken')->name('update');
        Route::delete('{token}', 'CcpsCore\AccountController@revokeToken')->name('revoke');
    });

    Route::group(['prefix' => 'notifications'], function () {
        Route::get('/', 'CcpsCore\AccountController@notifications')->name('account.notifications.index');
        Route::get('/channels/create', 'CcpsCore\AccountController@createChannel')->name('account.notifications.channels.create');
        Route::post('/channels/create', 'CcpsCore\AccountController@storeChannel')->name('account.notifications.channels.store');
        Route::delete('/channels/{channel}', 'CcpsCore\AccountController@destroyChannel')->name('account.notifications.channels.destroy');
        Route::get(
            '/channels/{channel}/resend-verification',
            'CcpsCore\ChannelVerificationController@resend'
        )->name('account.notifications.channels.resend-verification');
        Route::get(
            '/channels/{channel}/verify',
            'CcpsCore\ChannelVerificationController@verify'
        )->name('account.notifications.channels.verify');
        Route::get(
            '/channels/{channel}/test',
            'CcpsCore\ChannelVerificationController@test'
        )->name('account.notifications.channels.test');

        Route::get('/configure', 'CcpsCore\AccountController@configure')->name('account.notifications.configure');
        Route::post('/configure', 'CcpsCore\AccountController@configureSave')->name('account.notifications.configure.save');
    });
});

// CCPS Core routes
Uncgits\Ccps\Support\Facades\CcpsCore::routes();

// For local auth
Auth::routes();

// Socialite - User Account OAuth Routes
Route::get('auth/{provider}', 'CcpsCore\AuthController@redirectToProvider')->name('oauth');
Route::get('auth/{provider}/callback', 'CcpsCore\AuthController@handleProviderCallback')->name('oauth.callback');

Route::get('/', 'CanvasController@index')->name('home');

Route::prefix('live')->name('live.')->group(function () {
    Route::get('accounts', 'Canvas\Live\AccountsController@index')->name('accounts.index');


    Route::prefix('courses')->name('courses.')->group(function () {
        Route::get('/', 'Canvas\Live\CourseController@index')->name('index');
        Route::get('/show', 'Canvas\Live\CourseController@show')->name('show');
        Route::get('/download-enrollments', 'Canvas\Live\CourseController@downloadEnrollments')->name('download-enrollments');
    });

    Route::prefix('users')->name('users.')->group(function () {
        Route::get('/', 'Canvas\Live\UserController@index')->name('index');
        Route::get('/show', 'Canvas\Live\UserController@show')->name('show');
        Route::get('/course', 'Canvas\Live\UserController@course')->name('course');
        Route::get('/courses', 'Canvas\Live\UserController@courses')->name('courses');
    });

    Route::prefix('enrollments')->name('enrollments.')->group(function () {
        Route::get('/', 'Canvas\Live\EnrollmentController@index')->name('index');
        Route::get('/download', 'Canvas\Live\EnrollmentController@download')->name('download-user-enrollments');
    });

    Route::prefix('lookups')->name('lookups.')->group(function () {
        Route::get('/', 'Canvas\Live\LiveLookupController@index')->name('index');
    });
});

Route::prefix('courses')->name('courses.')->group(function () {
    Route::get('/create', 'Canvas\CourseController@create')->name('create');
    Route::post('/create', 'Canvas\CourseController@store')->name('store');
    Route::patch('/update', 'Canvas\CourseController@update')->name('update');

    Route::get('/list-roles-select-element', 'Canvas\CourseController@listRolesSelectElement')->name('list-roles-select-element');
    Route::post('/removeSisId', 'Canvas\CourseController@removeSisId')->name('removeSisId');
});

Route::group(['prefix' => 'crosslist'], function () {
    Route::get('/index', 'Canvas\CrosslistController@index')->name('crosslist.index');
    Route::get('/create', 'Canvas\CrosslistController@create')->name('crosslist.create');
    Route::redirect('/bulk', '/crosslist/create');
    Route::get('/decrosslist', 'Canvas\CrosslistController@decrosslist')->name('crosslist.decrosslist');
    Route::post('/destroy', 'Canvas\CrosslistController@destroy')->name('crosslist.destroy');
    Route::get('/report', 'CrosslistController@index')->name('crosslist-report.index');
});

Route::group(['prefix' => 'enrollmentrequests'], function () {
    Route::get('/', 'Canvas\EnrollmentrequestsController@index')->name('enrollmentrequests.index');
    Route::get('/all', 'Canvas\EnrollmentrequestsController@all')->name('enrollmentrequests.all');
    Route::get('/create', 'Canvas\EnrollmentrequestsController@create')->name('enrollmentrequests.create');
    Route::get('/show', 'Canvas\EnrollmentrequestsController@show')->name('enrollmentrequests.show');
    Route::get('/{enrollmentRequest}/edit', 'Canvas\EnrollmentrequestsController@edit')->name('enrollmentrequests.edit');
    Route::patch('/{enrollmentRequest}', 'Canvas\EnrollmentrequestsController@update')->name('enrollmentrequests.update');
    Route::get('/delete', 'Canvas\EnrollmentrequestsController@delete')->name('enrollmentrequests.delete');

    Route::get(
        '/create-in-canvas',
        'Canvas\EnrollmentrequestsController@createInCanvas'
    )->name('enrollmentrequests.create-in-canvas');
    Route::get('/reject', 'Canvas\EnrollmentrequestsController@reject')->name('enrollmentrequests.reject');

    Route::post('/store', 'Canvas\EnrollmentrequestsController@store')->name('enrollmentrequests.store');
    Route::delete(
        '/destroy',
        'Canvas\EnrollmentrequestsController@destroy'
    )->name('enrollmentrequests.destroy');

    Route::get(
        '/list-accounts',
        'Canvas\EnrollmentrequestsController@listAccounts'
    )->name('enrollmentrequests.list-accounts');
    Route::get(
        '/list-roles',
        'Canvas\EnrollmentrequestsController@listRoles'
    )->name('enrollmentrequests.list-roles');
    Route::get(
        '/list-roles-select-element',
        'Canvas\EnrollmentrequestsController@listRolesSelectElement'
    )->name('enrollmentrequests.list-roles-select-element');
});


Route::group(['prefix' => 'lti'], function () {
    Route::get('/', 'Canvas\LtiController@index')->name('lti.index');
    Route::get('/tool-edit', 'Canvas\LtiController@tooledit')->name('lti.tool.edit');
    Route::get('/tool-delete', 'Canvas\LtiController@tooldelete')->name('lti.tool.delete');
    Route::get('/tool-create', 'Canvas\LtiController@toolcreate')->name('lti.tool.create');
    Route::patch('/tool-update', 'Canvas\LtiController@toolupdate')->name('lti.tool.update');
    Route::post('/tool-store', 'Canvas\LtiController@toolstore')->name('lti.tool.store');
    Route::post('/tool-destroy', 'Canvas\LtiController@tooldestroy')->name('lti.tool.destroy');

    Route::get('/inventory', 'Canvas\LtiController@inventory')->name('lti.inventory.index');
    Route::get('/inventory-edit', 'Canvas\LtiController@inventoryedit')->name('lti.inventory.edit');
    Route::get('/inventory-delete', 'Canvas\LtiController@inventorydelete')->name('lti.inventory.delete');
    Route::get('/inventory-create', 'Canvas\LtiController@inventorycreate')->name('lti.inventory.create');
    Route::patch('/inventory-update', 'Canvas\LtiController@inventoryupdate')->name('lti.inventory.update');
    Route::post('/inventory-store', 'Canvas\LtiController@inventorystore')->name('lti.inventory.store');
    Route::post('/inventory-destroy', 'Canvas\LtiController@inventorydestroy')->name('lti.inventory.destroy');

    Route::get('/enrollment', 'Canvas\LtiController@enrollment')->name('lti.enrollment.index');
});

Route::group(['prefix' => 'page-view-audits'], function () {
    Route::get('/', 'Canvas\PageViewAuditController@index')->name('canvas.page-view-audits.index');
    Route::post('/results', 'Canvas\PageViewAuditController@results')->name('canvas.page-view-audits.results');
});

Route::group(['prefix' => 'nav-item-replacer'], function () {
    Route::get('/', 'NavItemReplacerController@index')->name('canvas.nav-item-replacer.index');
    Route::post('/review', 'NavItemReplacerController@review')->name('canvas.nav-item-replacer.review');
    Route::post('/', 'NavItemReplacerController@replace')->name('canvas.nav-item-replacer.replace');
});

Route::group(['prefix' => 'course-activity-report'], function () {
    Route::get('/', 'CourseActivityReportController@index')->name('canvas.course-activity-report.index');

app/CourseReport.php
<?php

namespace App;

use App\CcpsCore\User;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class CourseReport extends Model
{
    protected $guarded = [];
    public $timestamps = false;

    protected $dates = [
        'created_at',
        'completed_at',
    ];

    // relationships

    public function requestor()
    {
        return $this->belongsTo(User::class, 'requested_by');
    }

    public function course_report_items()
    {
        return $this->hasMany(CourseReportItem::class);
    }

    // aliases

    public function items()
    {
        return $this->course_report_items();
    }

    // accessors

    public function getPendingItemsAttribute()
    {
        return $this->course_report_items()->where('status', '=', 'pending')->get();
    }

    public function getStatusHtmlAttribute()
    {
        if (is_null($this->completed_at)) {
            return '<span class="text-info"><i class="fas fa-pause"></i> pending</span>';
        }

        if ($this->items()->where('status', 'error')->get()->isNotEmpty()) {
            return '<span class="text-warning"><i class="fas fa-exclamation-triangle"></i> complete (with errors)</span>';
        }

        return '<span class="text-success"><i class="fas fa-check"></i> complete</span>';
    }

    public function getCsvNameAttribute()
    {
        $now = Carbon::now()->format('Ymd_His');

        return "course-activity-report-{$this->id}-{$now}.csv";
    }

    // mutators

    public function getOptionsAttribute($value)
    {
        return json_decode($value);
    }
}

app/CourseReportItem.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class CourseReportItem extends Model
{
    protected $guarded = [];

    // relationships

    public function course_report()
    {
        return $this->belongsTo(CourseReport::class);
    }

    // aliases

    public function report()
    {
        return $this->course_report();
    }

    // accessors

    public function getStatusClassAttribute()
    {
        switch ($this->status) {
            case 'pending':
                return 'text-warning';
            case 'complete':
                return 'text-success';
            case 'error':
                return 'text-danger';
            default:
                return '';
        }
    }

    public function getStatusIconAttribute()
    {
        switch ($this->status) {
            case 'pending':
                return 'fas fa-pause';
            case 'complete':
                return 'fas fa-check';
            case 'error':
                return 'fas fa-exclamation-triangle';
            default:
                return '';
        }
    }

    public function getCourseUrlAttribute()
    {
        return config('cst.canvas_environment_url') . '/courses/' . $this->course_information->id;
    }

    public function getCourseStatusHtmlAttribute()
    {
        switch ($this->course_information->workflow_state) {
            case 'unpublished':
                return '<span class="text-danger">unpublished</span>';
            case 'available':
                return '<span class="text-success">available</span>';
            case 'completed':
                return '<span class="text-warning">completed</span>';
            case 'deleted':
                return '<span class="text-danger">deleted</span>';
            default:
                return '';
        }
    }

    public function getTeacherEmailsAttribute()
    {
        $teachers = $this->course_information->teachers;
        if (is_null($teachers) || count($teachers) == 0) {
            return [];
        }

        return array_map(function ($teacher) {
            return strtolower($teacher->login_id . '@uncg.edu');
        }, $teachers);
    }

    public function getEndsAtAttribute()
    {
        if (!isset($this->course_information->end_date) || is_null($this->course_information->end_date)) {
            return '';
        }

        return Carbon::parse($this->course_information->end_date)->toDateString();
    }

    // mutators

    public function getStatisticsAttribute($value)
    {
        return json_decode($value);
    }

    public function getCourseInformationAttribute($value)
    {
        return json_decode($value);
    }

    // other methods

    public function is_out_of_bounds($date)
    {
        $since = $this->report->options->since;
        $until = $this->report->options->until;
        if (is_null($since) && is_null($until)) {
            return false;
        }

        if (is_null($date) || empty($date)) {
            return true;
        }

        $date = Carbon::parse($date);

        return ($date->lt(Carbon::parse($since))) || ($date->gt(Carbon::parse($until)));
    }
}

app/Http/Controllers/Canvas/CrosslistController.php
<?php

namespace App\Http\Controllers\Canvas;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CrosslistController extends Controller
{
    public function __construct()
    {
        // Basic ACL middleware using Laratrust
        $this->middleware('permission:crosslist.create')->except(['index']);
        $this->middleware('permission:crosslist.delete')->except(['index']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\View\View
     */
    public function index()
    {
        return view('canvas.crosslist.index');
    }

    public function decrosslist()
    {
        return view('canvas.crosslist.decrosslist');
    }

    public function destroy(Request $request)
    {
        $sectionId = $request->get('section_id_field', '') !== 'canvas' ?
            'sis_section_id:' . $request->section_id :
            $request->section_id;

        $result = \CanvasApi::using('sections')->decrosslistSection($sectionId);

        $messageLevel = 'success';
        $message = 'De-Crosslist Successful: Section ' . $request->section_id;

        if ($result->getStatus() !== 'success') {
            $messageLevel = 'error';
            $lastResult = $result->getLastResult();
            $message = 'De-Crosslist NOT Successful: Section ' . $request->section_id . '. CODE:REASON: ' . $lastResult['code'] . ':' . $lastResult['reason'];
        }

        flash($message)->$messageLevel();

        \Log::channel('crosslist')->info($message, [
            'category'  => 'crosslist',
            'operation' => 'decrosslist',
            'result'    => $messageLevel,
            'data'      => [
                'user'                 => \Auth::user()->email,
                'child_section_sis_id' => $request->section_id,
            ]
        ]);

        return redirect(route('crosslist.index'));
    }



    public function create()
    {
        return view('canvas.crosslist.create');
    }
}

app/Http/Controllers/Canvas/Live/AccountsController.php
<?php

namespace App\Http\Controllers\Canvas\Live;

use App\Http\Controllers\Controller;
use App\Csthelpers\Generatearraytreeforaccountlist;

class AccountsController extends Controller
{
    public function __construct()
    {
        $this->middleware('permission:canvas.accounts.view');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\View\View
     */
    public function index()
    {
        $accountList = Generatearraytreeforaccountlist::createSimpleAccountsArrayForSelectElement();
        return view('live.accounts.index', compact('accountList'));
    }
}

app/Http/Controllers/CanvasController.php
<?php

namespace App\Http\Controllers;

class CanvasController extends Controller
{
    public function __construct()
    {
        // Basic ACL middleware using Laratrust
        $this->middleware('role:canvas.admin|servicedesk.member|lti.reader|itc');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\View\View
     */
    public function index()
    {
        return view('index');
    }
}

resources/views/canvas/course-activity-report/create.blade.php
@extends('layouts.wrapper', [
    'pageTitle' => 'Course Activity Report'
])

@section('head')
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet"/>

    <style>
        .form-check-input {
            position: static;
        }

        input[type="checkbox"] {
            margin-right: 10px;
        }
    </style>
@endsection

@section('content')
    <h1>Course Activity Report</h1>

    <p>This report will fetch activity data on each course within the search parameters.</p>

    {!! Form::open()->route('canvas.course-activity-report.store')->method('post')->fill(collect(session()->getOldInput())) !!}

    <div class="row mb-3">
        <div class="col-6">
            <div class="card">
                <div class="card-header">Required items</div>
                <div class="card-body">
                    {!! Form::select('account', 'Account', $accounts)->required(true)->help('Choose an account to search') !!}
                    {!! Form::select('term', 'Term', $terms)->required(true)->help('Choose a term to search') !!}
                </div>
            </div>
        </div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">Optional items</div>
                <div class="card-body">
                    {!! Form::checkbox('hide_empty', 'Hide Empty Courses?', 1)->required(false) !!}
                    <br>
                    {!! Form::text('since', 'Since (lower bound)')->required(false)->help('Choose a date to use as the lower bound for this report. The report will look for any activity in the course(s) since this date (inclusive)') !!}
                    {!! Form::text('until', 'Until (upper bound)')->required(false)->help('Choose a date to use as the upper bound for this report. The report will look for any activity in the course(s) until this date (exclusive)') !!}
                    {!! Form::text('search_term', 'Search Term')->help('If supplied, will fetch only Courses matching the search term in the name, code, or ID. Minimum 3 characters')->required(false) !!}
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col mb-3">
            {!! Form::submit('<i class="fas fa-check"></i> Begin report generation')->color('success') !!}
        </div>
    </div>
    {!! Form::close() !!}
@endsection()

@section('scripts')
    <script src="//code.jquery.com/ui/1.11.2/jquery-ui.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
    <script>
        $('#since').datepicker();
        $('#until').datepicker();
        // $('#account').select2();
        // $('#term').select2();
    </script>
@endsection

resources/views/canvas/course-activity-report/index.blade.php
@extends('layouts.wrapper', [
    'pageTitle' => 'Course Activity Reports'
])

@section('head')
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
@endsection

@section('content')
    <div class="row">
        <div class="col-6">
            <h1>Course Activity Reports</h1>
        </div>
        <div class="col-6 d-flex justify-content-end align-items-center">
            <a href="{{ route('canvas.course-activity-report.create') }}" class="btn btn-success btn-sm"><i
                        class="fas fa-plus"></i> New Report</a>
        </div>
    </div>

    @if($reports->isNotEmpty())
        <table class="table table-sm table-hover">
            <thead class="thead-light">
            <tr>
                <th>ID</th>
                <th>Requested By</th>
                <th>Account</th>
                <th>Term</th>
                <th>Status</th>
                <th>Queries Done</th>
                <th>Created At</th>
                <th>Completed At</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            @foreach($reports as $report)
                <tr>
                    <td>{{ $report->id }}</td>
                    <td>{{ $report->requestor->email }}</td>
                    <td>{{ $report->account_id }}</td>
                    <td>{{ $report->term_id }}</td>
                    <td>{!! $report->status_html !!}</td>
                    <td>{{ $report->items->count() - $report->pending_items->count() }}
                        / {{ $report->items->count() }}</td>
                    <td>{{ $report->created_at }}</td>
                    <td>{{ $report->completed_at }}</td>
                    <td>
                        <a href="{{ route('canvas.course-activity-report.show', ['report' => $report]) }}"
                           class="btn btn-info btn-sm">
                            <i class="fas fa-info-circle"></i> Details
                        </a>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    @else
        <p>No Activity Reports have been generated.</p>
    @endif

@endsection()

resources/views/canvas/course-activity-report/show.blade.php
@extends('layouts.wrapper', [
    'pageTitle' => 'Course Activity Report | Details: ' . $report->id
])

@section('content')
    <div class="row">
        <div class="col-6">
            <h1>Course Activity Report: {{ $report->id }}</h1>
        </div>
        <div class="col-6 d-flex justify-content-end align-items-center">
            <a href="{{ route('canvas.course-activity-report.index') }}" class="btn btn-sm btn-warning">
                <i class="fas fa-arrow-left"></i> Back
            </a>
        </div>
    </div>


    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header">Basic Information</div>
                <div class="card-body">
                    <p><strong>Requested by</strong>: {{ $report->requestor->email }}</p>
                    <p><strong>Status</strong>: {!! $report->status_html !!}</p>
                    <p><strong>Created at</strong>: {{ $report->created_at }}</p>
                    <p><strong>Completed at</strong>: {{ $report->completed_at }}</p>
                </div>
            </div>
        </div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">Options / Search Parameters</div>
                <div class="card-body">
                    <p><strong>Account ID</strong>: <a
                                href="{{ config('cst.canvas_environment_url') }}/accounts/{{ $report->account_id }}"
                                target="_blank">{{ $report->account_id }}</a>
                    </p>
                    <p><strong>Term ID</strong>: <a
                                href="{{ config('cst.canvas_environment_url') }}/accounts/1/terms"
                                target="_blank">{{ $report->term_id }}</a>
                    </p>
                    <p><strong>Options</strong>:</p>
                    <ul>
                        @foreach($report->options as $key => $value)
                            <li><strong>{{ $key }}</strong>: {{ $value }}</li>
                        @endforeach
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col">
            <div class="row">
                <div class="col-8">
                    <h1>Courses queried</h1>
                    @if(isset($report->options->since))
                        <p>Activity lower bound: <span class="text-danger">{{ $report->options->since }}</span>.
                            Activity before that time will be highlighted in <span class="text-danger">red</span>.</p>
                    @endif
                    @if(isset($report->options->until))
                        <p>Activity upper bound: <span class="text-danger">{{ $report->options->until }}</span>.
                            Activity after that time will be highlighted in <span class="text-danger">red</span>.</p>
                    @endif
                </div>
                <div class="col-4 d-flex justify-content-end align-items-center">
                    @if(!is_null($report->completed_at))
                        <a href="{{ route('canvas.course-activity-report.export', ['report' => $report]) }}"
                           class="btn btn-sm btn-success">
                            <i class="fas fa-file-csv"></i> Export to CSV
                        </a>
                    @endif
                </div>
            </div>
            @if($report->items->isNotEmpty())
                <table class="table table-sm table-striped">
                    <thead class="thead-light">
                    <tr>
                        <th>ID</th>
                        <th>Progress</th>
                        <th>Course</th>
                        <th>Status</th>
                        <th>End Date</th>
                        <th># Stu</th>
                        <th>Tot Time sec</th>
                        <th>Tch Activity</th>
                        <th>Stu View</th>
                        <th>Stu Partic</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($report->items as $item)
                        <tr>
                            <td>{{ $item->id }}</td>
                            <td class="{{ $item->status_class }}">
                                <i class="{{ $item->status_icon }}"></i>
                                {{ $item->status }}
                            </td>
                            <td>
                                <small>
                                    <a href="{{ $item->course_url }}"
                                       target="_blank">{{ $item->course_information->name }}</a>
                                </small>
                            </td>
                            <td>
                                {!! $item->course_status_html !!}
                            </td>
                            <td class="{{ $item->is_out_of_bounds($item->ends_at) ? 'text-danger' : '' }}">{{ $item->ends_at ?? 'none' }}</td>
                            <td>{{ $item->course_information->total_students }}</td>
                            <td>{{ optional($item->statistics)->total_activity_seconds ?? 'n/a' }}</td>
                            @include('canvas.course-activity-report.partials.activity-cell', ['attribute' => 'last_teacher_activity'])
                            @include('canvas.course-activity-report.partials.activity-cell', ['attribute' => 'last_student_view'])
                            @include('canvas.course-activity-report.partials.activity-cell', ['attribute' => 'last_student_participation'])

                        </tr>
                    @endforeach
                    </tbody>
                </table>
            @else
                <p>No items for this report.</p>
            @endif
        </div>
    </div>
@endsection()