routes/web.php
    Route::prefix('users')->name('users.')->group(function () {
        Route::get('/', 'Canvas\Live\UserController@index')->name('index');
        Route::get('/show', 'Canvas\Live\UserController@show')->name('show');
        Route::get('/course', 'Canvas\Live\UserController@course')->name('course');
        Route::get('/courses', 'Canvas\Live\UserController@courses')->name('courses');
    });

    Route::prefix('enrollments')->name('enrollments.')->group(function () {
        Route::get('/', 'Canvas\Live\EnrollmentController@index')->name('index');
        Route::get('/download', 'Canvas\Live\EnrollmentController@download')->name('download-user-enrollments');
    });

    Route::prefix('lookups')->name('lookups.')->group(function () {
        Route::get('/', 'Canvas\Live\LiveLookupController@index')->name('index');
    });
});

Route::prefix('courses')->name('courses.')->group(function () {
    Route::get('/create', 'Canvas\CourseController@create')->name('create');
    Route::post('/create', 'Canvas\CourseController@store')->name('store');
    Route::patch('/update', 'Canvas\CourseController@update')->name('update');

    Route::get('/list-roles-select-element', 'Canvas\CourseController@listRolesSelectElement')->name('list-roles-select-element');
    Route::post('/removeSisId', 'Canvas\CourseController@removeSisId')->name('removeSisId');
});

Route::group(['prefix' => 'crosslist'], function () {
    Route::get('/index', 'Canvas\CrosslistController@index')->name('crosslist.index');
    Route::get('/create', 'Canvas\CrosslistController@create')->name('crosslist.create');
    Route::redirect('/bulk', '/crosslist/create');
    Route::get('/decrosslist', 'Canvas\CrosslistController@decrosslist')->name('crosslist.decrosslist');
    Route::post('/destroy', 'Canvas\CrosslistController@destroy')->name('crosslist.destroy');
    Route::get('/report', 'CrosslistController@index')->name('crosslist-report.index');
});

Route::group(['prefix' => 'enrollmentrequests'], function () {
    Route::get('/', 'Canvas\EnrollmentrequestsController@index')->name('enrollmentrequests.index');
    Route::get('/all', 'Canvas\EnrollmentrequestsController@all')->name('enrollmentrequests.all');
    Route::get('/create', 'Canvas\EnrollmentrequestsController@create')->name('enrollmentrequests.create');
    Route::get('/show', 'Canvas\EnrollmentrequestsController@show')->name('enrollmentrequests.show');
    Route::get('/{enrollmentRequest}/edit', 'Canvas\EnrollmentrequestsController@edit')->name('enrollmentrequests.edit');
    Route::patch('/{enrollmentRequest}', 'Canvas\EnrollmentrequestsController@update')->name('enrollmentrequests.update');
    Route::get('/delete', 'Canvas\EnrollmentrequestsController@delete')->name('enrollmentrequests.delete');

    Route::get(
        '/create-in-canvas',
        'Canvas\EnrollmentrequestsController@createInCanvas'
    )->name('enrollmentrequests.create-in-canvas');
    Route::get('/reject', 'Canvas\EnrollmentrequestsController@reject')->name('enrollmentrequests.reject');

    Route::post('/store', 'Canvas\EnrollmentrequestsController@store')->name('enrollmentrequests.store');
    Route::delete(
        '/destroy',
        'Canvas\EnrollmentrequestsController@destroy'
    )->name('enrollmentrequests.destroy');

    Route::get(
        '/list-accounts',
        'Canvas\EnrollmentrequestsController@listAccounts'
    )->name('enrollmentrequests.list-accounts');
    Route::get(
        '/list-roles',
        'Canvas\EnrollmentrequestsController@listRoles'
    )->name('enrollmentrequests.list-roles');
    Route::get(
        '/list-roles-select-element',
        'Canvas\EnrollmentrequestsController@listRolesSelectElement'
    )->name('enrollmentrequests.list-roles-select-element');
});


Route::group(['prefix' => 'lti'], function () {
    Route::get('/', 'Canvas\LtiController@index')->name('lti.index');
    Route::get('/tool-edit', 'Canvas\LtiController@tooledit')->name('lti.tool.edit');
    Route::get('/tool-delete', 'Canvas\LtiController@tooldelete')->name('lti.tool.delete');
    Route::get('/tool-create', 'Canvas\LtiController@toolcreate')->name('lti.tool.create');
    Route::patch('/tool-update', 'Canvas\LtiController@toolupdate')->name('lti.tool.update');
    Route::post('/tool-store', 'Canvas\LtiController@toolstore')->name('lti.tool.store');
    Route::post('/tool-destroy', 'Canvas\LtiController@tooldestroy')->name('lti.tool.destroy');

    Route::get('/inventory', 'Canvas\LtiController@inventory')->name('lti.inventory.index');
    Route::get('/inventory-edit', 'Canvas\LtiController@inventoryedit')->name('lti.inventory.edit');
    Route::get('/inventory-delete', 'Canvas\LtiController@inventorydelete')->name('lti.inventory.delete');
    Route::get('/inventory-create', 'Canvas\LtiController@inventorycreate')->name('lti.inventory.create');
    Route::patch('/inventory-update', 'Canvas\LtiController@inventoryupdate')->name('lti.inventory.update');
    Route::post('/inventory-store', 'Canvas\LtiController@inventorystore')->name('lti.inventory.store');
    Route::post('/inventory-destroy', 'Canvas\LtiController@inventorydestroy')->name('lti.inventory.destroy');

    Route::get('/enrollment', 'Canvas\LtiController@enrollment')->name('lti.enrollment.index');
});

Route::group(['prefix' => 'page-view-audits'], function () {
    Route::get('/', 'Canvas\PageViewAuditController@index')->name('canvas.page-view-audits.index');
    Route::post('/results', 'Canvas\PageViewAuditController@results')->name('canvas.page-view-audits.results');
});

Route::group(['prefix' => 'nav-item-replacer'], function () {
    Route::get('/', 'NavItemReplacerController@index')->name('canvas.nav-item-replacer.index');
    Route::post('/review', 'NavItemReplacerController@review')->name('canvas.nav-item-replacer.review');
    Route::post('/', 'NavItemReplacerController@replace')->name('canvas.nav-item-replacer.replace');
});

Route::group(['prefix' => 'course-activity-report'], function () {
    Route::get('/', 'CourseActivityReportController@index')->name('canvas.course-activity-report.index');
    Route::get('/create', 'CourseActivityReportController@create')->name('canvas.course-activity-report.create');
    Route::post('/create', 'CourseActivityReportController@store')->name('canvas.course-activity-report.store');
    Route::get('/{report}', 'CourseActivityReportController@show')->name('canvas.course-activity-report.show');
    Route::get(
        '/{report}/export',
        'CourseActivityReportController@export'
    )->name('canvas.course-activity-report.export');
});

Route::prefix('quiz-log-reports')->name('canvas.quiz-log-reports.')->group(function () {
    Route::get('/', 'QuizLogReportController@index')->name('index');
    Route::get('create', 'QuizLogReportController@create')->name('create');
    Route::get('{report}', 'QuizLogReportController@show')->name('show');
    Route::get('{report}/download', 'QuizLogReportController@download')->name('download');
    Route::post('create', 'QuizLogReportController@store')->name('store');
    Route::post('loadCourseData', 'QuizLogReportController@loadCourseData')->name('load-course-data');
});

Route::group(['prefix' => 'lti-reports'], function () {
    Route::get('/', 'LtiReportController@index')->name('canvas.lti-reports.index');
    Route::get('/create', 'LtiReportController@create')->name('canvas.lti-reports.create');
    Route::post('/create', 'LtiReportController@store')->name('canvas.lti-reports.store');

    Route::get('/reports-select-element', 'LtiReportController@getReportTypesSelectElementForAccount')
        ->name('canvas.lti-reports.reports-select-element');

    Route::get('/{report}', 'LtiReportController@show')->name('canvas.lti-reports.show');
    Route::get('/{report}/export', 'LtiReportController@export')->name('canvas.lti-reports.export');
});


Route::prefix('manual-enrollments')->name('manual-enrollments.')->group(function () {
    Route::get('/', 'ManualEnrollmentController@index')->name('index');
    Route::get('/create', 'ManualEnrollmentController@create')->name('create');
    Route::get('/list-roles-select-element', 'ManualEnrollmentController@listRolesSelectElement')->name('list-roles-select-element');
    Route::post('/store', 'ManualEnrollmentController@store')->name('store');
    Route::patch('/{manualEnrollmentBatch}', 'ManualEnrollmentController@update')->name('update');
    Route::get('/{manualEnrollmentBatch}', 'ManualEnrollmentController@show')->name('show');
    Route::post('/{manualEnrollment}/retry', 'ManualEnrollmentController@retry')->name('retry');
    Route::post('/{manualEnrollmentBatch}/retry-all', 'ManualEnrollmentController@retryAll')->name('retry-all');
});

Route::prefix('lti-editor')->name('lti-editor.')->group(function () {
    Route::get('/', 'LtiEditorController@index')->name('index');
    Route::get('/edit', 'LtiEditorController@edit')->name('edit');
    Route::patch('/{toolId}', 'LtiEditorController@update')->name('update');
    Route::post('/load-tools', 'LtiEditorController@loadTools')->name('load-tools');
});

Route::prefix('nav-item-reports')->name('nav-item-reports.')->group(function () {
    Route::get('/', 'NavItemReportController@index')->name('index');
    Route::get('{report}', 'NavItemReportController@show')->name('show');
});

Route::prefix('batch-sandbox-courses')->name('batch-sandbox-courses.')->group(function () {
    Route::get('/', 'BatchSandboxCourseController@index')->name('index');
    Route::get('create', 'BatchSandboxCourseController@create')->name('create');
    Route::get('{batch}', 'BatchSandboxCourseController@show')->name('show');
});

// Horizon override
Route::group([
    'prefix'     => 'horizon',
    'namespace'  => 'Laravel\Horizon\Http\Controllers',
    'middleware' => config('horizon.middleware', 'web'),
], function () {
    // Catch-all Route...
    Route::get('/{view?}', '\App\Http\Controllers\CcpsCore\HomeController@horizon')->where(
        'view',
        '(.*)'
    )->name('horizon.index');

app/Models/ManualEnrollment.php
<?php

namespace App\Models;

use App\ManualEnrollmentBatch;
use Illuminate\Database\Eloquent\Model;

class ManualEnrollment extends Model
{
    protected $guarded = ['id', 'created_at', 'updated_at'];

    // relationships

    public function manual_enrollment_batch()
    {
        return $this->belongsTo(ManualEnrollmentBatch::class, 'batch_id');
    }

    // aliases

    public function batch()
    {
        return $this->manual_enrollment_batch();
    }

    // scopes

    public function scopeErrored($query)
    {
        return $query->whereIn('status', ['error']);
    }
}

resources/views/manual-enrollments/batch.blade.php
@extends('layouts.wrapper', [
    'pageTitle' => 'Manual Enrollment | Batch Status'
])

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading"><h5>Change Status of Entire Batch (regardless of current status)</h5></div>
                    <div class="panel-body">
                        <a href="{{ route('manualenrollments.index') }}" title="Back"><button class="btn btn-warning btn-xs"><i class="fa fa-arrow-left" aria-hidden="true"></i> Back</button></a>
                        <br />
                        <br />
                        @if ($errors->any())
                            <ul class="alert alert-danger">
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        @endif
                        <form method="POST" action="{{ route('manualenrollments.batch') }}" accept-charset="UTF-8" class="form-horizontal" enctype="multipart/form-data">
                            {{ csrf_field() }}
                            @include ('manualenrollments.form-batch')
                            <input type="hidden" name="created_at" id="created_at" value="{{ $manualenrollments[0]->created_at }}">
                        </form>
                        <br />
                        <h6>..or just requeue just the Errors</h6>
                        <form method="POST" action="{{ route('manualenrollments.requeueErrors') }}" accept-charset="UTF-8" class="form-horizontal" enctype="multipart/form-data">
                            {{ csrf_field() }}
                            <input type="hidden" name="created_at" id="created_at" value="{{ $manualenrollments[0]->created_at }}">
                            <div class="form-group">
                                <div class="col-md-offset-4 col-md-4">
                                    <input class="btn btn-primary" type="submit" value="Requeue Errors Now">
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <h3>Enrollments to be Updated:</h3>
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <div class="table-responsive">
                            <table class="table table-borderless">
                                <thead>
                                <tr>
                                    <th>Batch</th>
                                    <th>Action</th>
                                    <th>Course Or Section</th>
                                    <th>Type</th>
                                    <th>User Id</th>
                                    <th>Current Status</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($manualenrollments as $item)
                                    <tr>
                                        <td>{{ $item->created_at }}</td>
                                        <td>{{ $item->action }}</td>
                                        <td>{{ $item->course_or_section }}: {{ $item->course_or_section_id }}</td>
                                        <td>{{ $item->role_label }}</td>
                                        <td>{{ $item->user_id }}</td>
                                        <td>{{ $item->status }}</td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/manual-enrollments/create.blade.php
@extends('layouts.wrapper', [
    'pageTitle' => 'Manual Enrollment | Create'
])

@section('content')

<h2>New Manual Enrollment Batch</h2>
<p>Each set of Manual Enrollments will be created as a <strong>Batch</strong>, with each individual operation as a separate Manual Enrollment record.</p>

<hr>

{!! Form::open()->method('post')->route('manual-enrollments.store')->fill(collect(request()->old())) !!}

<div class="card mb-3">
    <div class="card-header">Destination Information</div>
    <div class="card-body">
        <div class="form-row">
            <div class="col">
                {!! Form::select('destination_type', 'Destination Type', ['section' => 'Section', 'course' => 'Course'])->required() !!}
            </div>
            <div class="col">
                {!! Form::text('destination_id', 'Destination ID')->required()->help('The Canvas Course ID or Section ID (not SIS ID)') !!}
            </div>
        </div>
        <div class="form-row">
            <div class="col text-center">
                <p>
                    <button type="button" class="btn btn-info" id="load_roles">
                        <i class="fas fa-cloud-download-alt"></i>
                        Load roles for course/section
                    </button>
                </p>
                <p>
                    <small id="loading-roles" class="d-none"><i class="fas fa-spin fa-spinner"></i> <span class="text-muted">Retrieving roles from Canvas...</span></small>
                    <small id="invalid-account-id" class="d-none"><span class="text-danger">Account roles could not be retrieved from Canvas</span></small>
                    <small id="valid-account-id" class="d-none"><span class="text-success"><i class="fa fa-check"></i> Account roles retrieved from Canvas</span></small>
                </p>
            </div>
        </div>
    </div>
</div>

<div class="card mb-3">
    <div class="card-header">Enrollment Information</div>
    <div class="card-body">
        <div class="form-row">
            <div class="col">
                {!! Form::text('account', 'Account')->placeholder('(Load roles first)')->readonly() !!}
                {!! Form::select('role_id', 'Role', ['' => '(Load roles first)'])->required()->disabled() !!}
                {!! Form::select('user_id_type', 'User ID Type', ['login_id' => 'SIS Login ID', 'canvas_id' => 'Canvas ID', 'sis_user_id' => 'SIS ID'])->required() !!}
            </div>
            <div class="col">
                <div class="form-group">
                    <label for="user_list">User IDs to Enroll</label>
                    <textarea rows="15" type="textarea" name="user_list" id="user_list" class="form-control" required=""></textarea>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="card mb-3">
    <div class="card-header">Additional Information</div>
    <div class="card-body">
        <div class="form-group">
            <label for="notes">Notes</label>
            <textarea rows="5" type="textarea" name="notes" id="notes" class="form-control"></textarea>
        </div>
    </div>
</div>

{!! Form::submit('<i class="fas fa-check"></i> Submit')->color('success')->attrs(['class' => 'mb-3']) !!}

@endsection

@section('scripts')

    <script>
        $("#load_roles").on('click', function() {

            $("#loading-roles").removeClass('d-none');
            $("#invalid-account-id").addClass('d-none');
            $("#valid-account-id").addClass('d-none');

            $.ajax({
                type: "GET",
                url: "{{ route('manual-enrollments.list-roles-select-element') }}",
                data: {
                    "destination_type": $("#destination_type").val(),
                    "destination_id": $("#destination_id").val(),
                }
            }).done(function (data, textStatus, jqXHR) {
                // console.log(data.data);
                $("#role_id").html(data.options).removeAttr('disabled');
                $("#account").val(data.account.id + " - " + data.account.name);
                $("#valid-account-id").removeClass('d-none');
            }).fail(function (jqXHR, textStatus, errorThrown) {
                // console.log(errorThrown, jqXHR);
                $("#role_id").html("<option value=\"\">(Account not found)</option>").attr('disabled', 'disabled')
                $("#account").val("(Account not found)")
                $("#invalid-account-id").removeClass('d-none');
            }).always(function (data, textStatus, jqXHR) {
                $("#loading-roles").addClass('d-none');
            });

        });
    </script>

@endsection

resources/views/manual-enrollments/edit.blade.php
@extends('layouts.wrapper', [
    'pageTitle' => 'Manual Enrollment | Edit'
])

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">Edit Manual Enrollment #{{ $manualenrollment->id }}</div>
                    <div class="panel-body">
                        <a href="{{ route('manualenrollments.index') }}" title="Back"><button class="btn btn-warning btn-xs"><i class="fa fa-arrow-left" aria-hidden="true"></i> Back</button></a>
                        <br />
                        <br />

                        @if ($errors->any())
                            <ul class="alert alert-danger">
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        @endif

                        <p>NOTE: If you need to edit the role, delete this item and then resubmit the form again.</p>

                        <form method="POST" action="{{ route('manualenrollments.update', $manualenrollment->id) }}" accept-charset="UTF-8" class="form-horizontal" enctype="multipart/form-data">
                            {{ method_field('PATCH') }}
                            {{ csrf_field() }}

                            @include ('manualenrollments.form', ['submitButtonText' => 'Update'])

                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')

    <script>

        $( "#accountId" ).change(function()
        {
            //this is the #state dom element
            var state = $(this).val();

            // parameter 1 : url
            // parameter 2: post data
            //parameter 3: callback function

            var thisAccountId = $( "#accountId option:selected" ).val();

            $.get( '{{ route('manualenrollments.list-roles-select-element') }}' + '?accountId=' + thisAccountId, { state : state } , function(htmlCode) { //htmlCode is the code returned from your controller
                $("#role-select-container").html(htmlCode);
            });
        });
    </script>

@endsection

resources/views/manual-enrollments/form-batch.blade.php
<div class="form-group {{ $errors->has('status') ? 'has-error' : ''}}">
    <label for="status" class="col-md-4 control-label">{{ 'Set New Status' }}</label>
    <div class="col-md-6">
        <select name="status" class="form-control" id="status">
            'pending-approval','approved-pending-upload','successfully-uploaded','error','canceled'
            @foreach (json_decode('{"pending-approval":"Pending Approval","approved-pending-upload":"Approved Pending Upload","canceled":"Canceled"}', true) as $optionKey => $optionValue)
                <option value="{{ $optionKey }}">{{ $optionValue }}</option>
            @endforeach
        </select>
        {!! $errors->first('status', '<p class="help-block">:message</p>') !!}
    </div>
</div>

<div class="form-group">
    <div class="col-md-offset-4 col-md-4">
        <input class="btn btn-primary" type="submit" value="{{ $submitButtonText ?? 'Update Now' }}">
    </div>
</div>

resources/views/manual-enrollments/index.blade.php
@extends('layouts.wrapper', [
    'pageTitle' => 'Manual Enrollments | Index'
])

@section('content')
    {!! Breadcrumbs::render('manual-enrollments.index') !!}

    <div class="row">
        <div class="col">
            <h1>Manual Enrollment Batches</h1>
        </div>
        <div class="col d-flex justify-content-end align-items-center">
            @permission('manual-enrollments.create')
            <a href="{{ route('manual-enrollments.create') }}" class="btn btn-success btn-sm" title="Add New Batch of Manual Enrollments">
                <i class="fa fa-plus" aria-hidden="true"></i> New Batch
            </a>
            @endpermission
        </div>
    </div>
    @permission('manual-enrollments.read')
        @if ($batches->isEmpty())
            <p>No batches to show.</p>
        @else
            @component('components.paginated-table', ['collection' => $batches])
                @slot('table')
                    @component('components.table')
                        @slot('th')
                            <th>ID</th>
                            <th>Created By</th>
                            <th>Destination</th>
                            <th>Status</th>
                            <th>Created At</th>
                            <th>Actions</th>
                        @endslot
                        @slot('tbody')
                            @foreach ($batches as $batch)
                                <tr>
                                    <td>{{ $batch->id }}</td>
                                    <td>{{ optional($batch->created_by_user)->email ?? '' }}</td>
                                    <td>{{ $batch->destination_type }}: {{ $batch->destination_id }}</td>
                                    <td>
                                        @include('partials.statuses.' . $batch->status)
                                    </td>
                                    <td>{{ $batch->created_at }}</td>
                                    <td class="d-flex justify-content-start align-items-center">
                                        <a href="{{ route('manual-enrollments.show', $batch) }}" class="btn btn-sm btn-info">
                                            <i class="fas fa-list"></i> Details
                                        </a>
                                        @include('manual-enrollments.partials.action-buttons')
                                    </td>
                                </tr>
                            @endforeach
                        @endslot
                    @endcomponent
                @endslot
            @endcomponent
        @endif
    @endpermission
@endsection

resources/views/manual-enrollments/list-accounts.blade.php
@extends('layouts.wrapper', [
    'pageTitle' => 'Manual Enrollments | List Accounts'
])

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="table-responsive">
                        <table class="table table-borderless">
                            <thead>
                                <th>ID</th>
                                <th>Account Name</th>
                                <th>Action</th>
                            </thead>
                            <tbody>
                                @foreach($result['results'] as $item)
                                <tr>
                                    <td>{{ $item->id }}</td>
                                    <td>{{ $item->name }}</td>
                                    <td><a href="{{route('manualenrollments.list-roles')}}?accountId={{$item->id}}" title="Select this account to view its roles"><btn class="btn btn-info">Select</btn></a></td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/manual-enrollments/role-select-element.blade.php
@isset($roles)
@foreach($roles as $role)
    <option value="{{ $role->id }}" >{{ $role->label }}</option>
@endforeach
@endisset

resources/views/manual-enrollments/show.blade.php
@extends('layouts.wrapper', [
    'pageTitle' => 'Manual Enrollment Batch | Show'
])

@section('content')
    {!! Breadcrumbs::render('manual-enrollments.show', $batch) !!}

    <h2>Manual Enrollment Batch #{{ $batch->id }}</h2>
    <div class="row">
        <div class="col-6">
            <div class="card mb-3">
                <div class="card-header">Batch information</div>
                <div class="card-body">
                    <p><strong>Created by</strong>: {{ optional($batch->created_by_user)->email ?? 'unknown (legacy record)' }}</p>
                    <p><strong>Created at</strong>: {{ $batch->created_at }}</p>
                    <p><strong>Destination</strong>: {{ $batch->destination_type }}: {{ $batch->destination_id }}</p>
                    <p><strong>Status</strong>: @include('partials.statuses.' . $batch->status)</p>
                    <p><strong>Notes</strong>: {{ $batch->notes }}</p>
                    <p><strong>Enrollment Count</strong>: {{ $enrollments->count() }}</p>
                </div>
            </div>
        </div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">Actions</div>
                <div class="card-body d-flex flex-content-start align-items-center">
                    @include('manual-enrollments.partials.action-buttons')
                </div>
            </div>

        </div>
    </div>
    <hr>
    <h3>Enrollments</h3>
    @if($batch->manual_enrollments->isEmpty())
        <p>Well that's strange. This Batch has no enrollments...</p>
    @else
        @component('components.paginated-table', ['collection' => $enrollments])
            @slot('table')
                @component('components.table')
                    @slot('th')
                        <th>User ID</th>
                        <th>User ID Type</th>
                        <th>Role</th>
                        <th>Status</th>
                        <th>Canvas Enrollment ID</th>
                        <th>Actions</th>
                    @endslot
                    @slot('tbody')
                        @foreach ($enrollments as $enrollment)
                        <tr>
                            <td>{{ $enrollment->enrolled_user_id }}</td>
                            <td>{{ $enrollment->enrolled_user_id_type }}</td>
                            <td>{{ $enrollment->role_type }}</td>
                            <td>
                                @include('partials.statuses.' . $enrollment->status)
                                @if ($enrollment->status === 'error')
                                    <!-- Button trigger modal -->
                                    <span class="ml-2" style="cursor: pointer;"><i class="fas fa-info-circle" data-toggle="modal" data-target="#error_{{ $enrollment->id }}"></i></span>
                                    @component('components.modal', [
                                        'title' => 'Error Details',
                                        'id' => 'error_' . $enrollment->id
                                    ])
                                        @slot('content')
                                            {{ $enrollment->notes }}
                                        @endslot
                                    @endcomponent
                                @endif
                            </td>
                            <td>{{ $enrollment->canvas_enrollment_id }}</td>
                            <td class="d-flex justify-content-start align-items-center">
                                @permission('manual-enrollments.update')
                                @if($enrollment->status === 'error')
                                    {!! Form::open()->post()->route('manual-enrollments.retry', ['manualEnrollment' => $enrollment]) !!}
                                    {!! Form::submit('<i class="fas fa-redo"></i> Retry')->attrs(['class' => 'btn btn-xs btn-danger mr-3']) !!}
                                    {!! Form::close() !!}
                                @endif
                                @endpermission
                            </td>
                        </tr>
                        @endforeach
                    @endslot
                @endcomponent
            @endslot
        @endcomponent
    @endif
@endsection